#!/usr/bin/env python3
"""
╔══════════════════════════════════════════════════════════════════════╗
║            LOG NORMALIZATION PIPELINE  v1.0                          ║
║            Web · Auth · System  →  Unified Schema                    ║
╚══════════════════════════════════════════════════════════════════════╝

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 QUICK-START GUIDE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

 STEP 1 ── No dependencies needed  (pure standard-library Python)

 STEP 2 ── Run the program
   python log_normalization_pipeline.py

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 MENU OPTIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

 1. Generate sample logs   – Create a fresh batch of raw log lines
                             from three simulated sources:
                             Apache web logs, SSH auth logs, syslog.

 2. Load logs from file    – Read raw log lines from a plain-text file
                             (one log entry per line).

 3. Run normalization      – Execute the full pipeline on raw logs:
                             Parse → Normalize → Validate → Tag.

 4. View raw logs          – Print the un-processed input lines so you
                             can compare them against the output.

 5. View normalized logs   – Pretty-print every normalized log record
                             in a structured, readable layout.

 6. View pipeline stats    – Show counts, tag breakdown, validation
                             failures, and per-source statistics.

 7. Export to JSON         – Save all normalized records to a JSON file
                             (default: normalized_logs.json).

 8. Exit

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 UNIFIED SCHEMA  (every normalized record contains these fields)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

   id            – Auto-incremented integer, unique per session
   timestamp     – ISO-8601 UTC string  (YYYY-MM-DDTHH:MM:SSZ)
   source        – Origin system label  (web_server | auth | system)
   category      – High-level tag       (web | auth | system)
   event_type    – Specific action      (e.g. http_request, login_failed)
   ip            – IPv4 address or null
   user          – Username string or null
   message       – Cleaned human-readable description
   status        – HTTP code / success / failure / info or null
   severity      – critical | high | medium | low | info
   raw           – Original un-modified log line (for audit trail)
   valid         – True if the record passed all validation rules

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 PIPELINE STAGES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

   Stage 1 – INPUT        Raw log strings enter the pipeline
   Stage 2 – DETECTION    Each line is matched to a source parser
   Stage 3 – PARSING      Regex extracts raw fields
   Stage 4 – NORMALIZATION Fields are mapped to the unified schema,
                           timestamps are converted to ISO-8601 UTC,
                           missing fields are filled with null
   Stage 5 – VALIDATION   Required fields checked, timestamp validity
                           confirmed, IP format verified
   Stage 6 – TAGGING      Category and severity labels are assigned
   Stage 7 – OUTPUT       Structured records ready for display / export

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 SUPPORTED LOG FORMATS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

 Apache Combined Log Format
   192.168.1.1 - frank [10/Oct/2024:13:55:36 -0700]
   "GET /index.html HTTP/1.1" 200 2326

 SSH / Auth Log Format  (syslog-style with process tag)
   Oct 10 13:55:36 webserver sshd[1234]:
   Failed password for root from 10.0.0.1 port 22 ssh2

 Syslog Format
   Oct 10 13:55:36 appserver kernel:
   [12345.678] Out of memory: Kill process 999

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 NOTES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

 • Unrecognised log lines are stored with source="unknown" and
   valid=False so nothing is silently dropped.
 • All timestamps are normalised to UTC ISO-8601 regardless of the
   timezone offset present in the original log.
 • The raw field is always preserved for audit / forensic purposes.
 • Logs generated by option 1 include intentional edge cases:
   malformed lines, missing fields, unusual timestamps.
"""

# ─────────────────────────────────────────────────────────────────────
#  STANDARD-LIBRARY IMPORTS  (no pip install required)
# ─────────────────────────────────────────────────────────────────────
import re
import json
import os
import sys
import random
import ipaddress
from datetime import datetime, timezone, timedelta
from copy import deepcopy
from typing import Optional

# ─────────────────────────────────────────────────────────────────────
#  COLOUR HELPERS
# ─────────────────────────────────────────────────────────────────────

class C:
    """ANSI colour codes; auto-disabled on Windows unless FORCE_COLOR is set."""
    _on = (sys.platform != "win32") or os.environ.get("FORCE_COLOR")
    RED     = "\033[91m" if _on else ""
    YELLOW  = "\033[93m" if _on else ""
    GREEN   = "\033[92m" if _on else ""
    CYAN    = "\033[96m" if _on else ""
    MAGENTA = "\033[95m" if _on else ""
    BLUE    = "\033[94m" if _on else ""
    BOLD    = "\033[1m"  if _on else ""
    DIM     = "\033[2m"  if _on else ""
    RESET   = "\033[0m"  if _on else ""

SEP  = "─" * 72
SEP2 = "═" * 72

def sev_colour(sev: str) -> str:
    """Return an ANSI colour for a severity label."""
    return {
        "critical": C.RED,
        "high":     C.RED,
        "medium":   C.YELLOW,
        "low":      C.CYAN,
        "info":     C.GREEN,
    }.get(sev.lower(), C.RESET)

def banner():
    print(f"""
{C.CYAN}{C.BOLD}
╔══════════════════════════════════════════════════════════════════════╗
║            LOG NORMALIZATION PIPELINE  v1.0                          ║
║            Web · Auth · System  →  Unified Schema                    ║
╚══════════════════════════════════════════════════════════════════════╝
{C.RESET}""")

# ─────────────────────────────────────────────────────────────────────
#  UNIFIED LOG RECORD SCHEMA
# ─────────────────────────────────────────────────────────────────────

# Counter used to assign unique IDs across the session
_id_counter = 0

def _next_id() -> int:
    global _id_counter
    _id_counter += 1
    return _id_counter

def empty_record(raw: str = "") -> dict:
    """
    Return a blank normalized record with every field set to its
    default/null value.  All parsers should start from this template
    so the schema is always complete.
    """
    return {
        "id":         _next_id(),
        "timestamp":  None,    # ISO-8601 UTC string after normalization
        "source":     "unknown",
        "category":   "unknown",
        "event_type": "unknown",
        "ip":         None,
        "user":       None,
        "message":    "",
        "status":     None,
        "severity":   "info",
        "raw":        raw,
        "valid":      False,
    }

# ─────────────────────────────────────────────────────────────────────
#  TIMESTAMP NORMALIZATION
# ─────────────────────────────────────────────────────────────────────

# Maps abbreviated month names to zero-padded numbers
_MONTHS = {
    "jan": "01", "feb": "02", "mar": "03", "apr": "04",
    "may": "05", "jun": "06", "jul": "07", "aug": "08",
    "sep": "09", "oct": "10", "nov": "11", "dec": "12",
}

def _apache_ts_to_iso(ts_str: str) -> Optional[str]:
    """
    Convert Apache Combined Log timestamp to ISO-8601 UTC.

    Input  : '10/Oct/2024:13:55:36 -0700'
    Output : '2024-10-10T20:55:36Z'
    """
    pattern = r"(\d{2})/(\w{3})/(\d{4}):(\d{2}):(\d{2}):(\d{2}) ([+-]\d{4})"
    m = re.match(pattern, ts_str.strip())
    if not m:
        return None
    day, mon, year, hh, mm, ss, tz = m.groups()
    month = _MONTHS.get(mon.lower())
    if not month:
        return None
    # Parse timezone offset into a timedelta
    sign   = 1 if tz[0] == "+" else -1
    tz_h   = int(tz[1:3])
    tz_m   = int(tz[3:5])
    offset = timedelta(hours=tz_h, minutes=tz_m) * sign
    try:
        naive  = datetime(int(year), int(month), int(day),
                          int(hh), int(mm), int(ss))
        utc_dt = naive - offset              # convert to UTC
        return utc_dt.strftime("%Y-%m-%dT%H:%M:%SZ")
    except ValueError:
        return None


def _syslog_ts_to_iso(ts_str: str, ref_year: int = None) -> Optional[str]:
    """
    Convert syslog-style timestamp to ISO-8601 UTC.

    Input  : 'Oct 10 13:55:36'
    Output : '2024-10-10T13:55:36Z'  (assumes local = UTC for syslog)

    Syslog traditionally omits the year; we default to the current year
    unless a reference year is supplied.
    """
    pattern = r"(\w{3})\s+(\d{1,2})\s+(\d{2}):(\d{2}):(\d{2})"
    m = re.match(pattern, ts_str.strip())
    if not m:
        return None
    mon, day, hh, mm, ss = m.groups()
    month = _MONTHS.get(mon.lower())
    if not month:
        return None
    year = ref_year or datetime.now(timezone.utc).year
    try:
        dt = datetime(year, int(month), int(day), int(hh), int(mm), int(ss))
        return dt.strftime("%Y-%m-%dT%H:%M:%SZ")
    except ValueError:
        return None


def _iso_passthrough(ts_str: str) -> Optional[str]:
    """
    Accept an already-ISO-ish timestamp and normalise it to UTC.

    Handles:
      2024-10-10T13:55:36Z
      2024-10-10 13:55:36
      2024-10-10T13:55:36+05:30
    """
    # Remove colon from offset so strptime can parse it
    ts_clean = re.sub(r"([+-])(\d{2}):(\d{2})$", r"\1\2\3", ts_str.strip())
    for fmt in ("%Y-%m-%dT%H:%M:%SZ",
                "%Y-%m-%dT%H:%M:%S",
                "%Y-%m-%d %H:%M:%S",
                "%Y-%m-%dT%H:%M:%S%z"):
        try:
            dt = datetime.strptime(ts_clean, fmt)
            if dt.tzinfo is None:
                dt = dt.replace(tzinfo=timezone.utc)
            utc = dt.astimezone(timezone.utc)
            return utc.strftime("%Y-%m-%dT%H:%M:%SZ")
        except ValueError:
            continue
    return None

# ─────────────────────────────────────────────────────────────────────
#  IP VALIDATION
# ─────────────────────────────────────────────────────────────────────

def _valid_ip(ip_str: str) -> bool:
    """Return True if ip_str is a valid IPv4 or IPv6 address."""
    try:
        ipaddress.ip_address(ip_str)
        return True
    except ValueError:
        return False

# ─────────────────────────────────────────────────────────────────────
#  PARSER  –  STAGE 2 / 3  (Detection + Field Extraction)
# ─────────────────────────────────────────────────────────────────────

# ── Apache Combined Log Format ───────────────────────────────────────
# 192.168.1.1 - frank [10/Oct/2024:13:55:36 -0700] "GET /index.html HTTP/1.1" 200 2326
_RE_APACHE = re.compile(
    r'(?P<ip>\S+)'            # client IP
    r'\s+\S+'                 # ident (usually -)
    r'\s+(?P<user>\S+)'       # authuser
    r'\s+\[(?P<ts>[^\]]+)\]'  # timestamp in brackets
    r'\s+"(?P<method>\S+)'    # HTTP method
    r'\s+(?P<path>\S+)'       # request path
    r'\s+\S+"'                # protocol
    r'\s+(?P<status>\d{3})'   # status code
    r'.*'                     # bytes + optional referrer/UA
)

def parse_apache(line: str) -> Optional[dict]:
    """
    Parse a single Apache Combined Log line.
    Returns a partially-filled record dict or None if regex fails.
    """
    m = _RE_APACHE.match(line)
    if not m:
        return None

    rec = empty_record(line)
    rec["source"]     = "web_server"
    rec["category"]   = "web"
    rec["ip"]         = m.group("ip")
    rec["user"]       = None if m.group("user") == "-" else m.group("user")
    rec["timestamp"]  = _apache_ts_to_iso(m.group("ts"))
    rec["status"]     = m.group("status")
    rec["message"]    = f'{m.group("method")} {m.group("path")} → {m.group("status")}'

    # Classify HTTP event type from method + status code
    status_int = int(m.group("status"))
    method     = m.group("method").upper()
    if status_int >= 500:
        rec["event_type"] = "http_server_error"
    elif status_int >= 400:
        rec["event_type"] = "http_client_error"
    elif method in ("POST", "PUT", "PATCH", "DELETE"):
        rec["event_type"] = "http_write"
    else:
        rec["event_type"] = "http_request"

    return rec


# ── SSH / Auth Log Format ─────────────────────────────────────────────
# Oct 10 13:55:36 webserver sshd[1234]: Failed password for root from 10.0.0.1 port 22 ssh2
# Oct 10 13:55:36 webserver sshd[1234]: Accepted publickey for alice from 10.0.0.2 port 22 ssh2
# Oct 10 13:55:36 webserver sudo: alice : TTY=pts/0 ; PWD=/home/alice ; USER=root ; COMMAND=/bin/bash
# Oct 10 13:55:36 webserver PAM[99]: Authentication failure; logname=bob uid=1001
_RE_AUTH_HEADER = re.compile(
    r"(?P<ts>\w{3}\s+\d{1,2}\s+\d{2}:\d{2}:\d{2})"  # syslog timestamp
    r"\s+\S+"                                           # hostname
    r"\s+(?P<proc>[^\[:]+)"                             # process name (sshd, sudo, PAM…)
    r"(?:\[\d+\])?"                                     # optional PID
    r":\s+(?P<msg>.+)"                                  # remainder
)
_RE_SSH_FAILED   = re.compile(r"Failed (?:password|publickey) for (?:invalid user )?(?P<user>\S+) from (?P<ip>\S+)")
_RE_SSH_ACCEPTED = re.compile(r"Accepted (?:password|publickey) for (?P<user>\S+) from (?P<ip>\S+)")
_RE_SSH_INVALID  = re.compile(r"Invalid user (?P<user>\S+) from (?P<ip>\S+)")
_RE_SUDO         = re.compile(r"(?P<user>\S+)\s+:.*COMMAND=(?P<cmd>.+)")
_RE_PAM_FAIL     = re.compile(r"Authentication failure.*logname=(?P<user>\S+)")
_RE_DISCONNECT   = re.compile(r"Disconnected from (?:invalid user )?(?P<user>\S+)?\s*(?P<ip>\d+\.\d+\.\d+\.\d+)")

def parse_auth(line: str) -> Optional[dict]:
    """Parse SSH, sudo, and PAM authentication log lines."""
    m = _RE_AUTH_HEADER.match(line)
    if not m:
        return None

    rec             = empty_record(line)
    rec["source"]   = "auth"
    rec["category"] = "auth"
    rec["timestamp"] = _syslog_ts_to_iso(m.group("ts"))
    proc            = m.group("proc").strip().lower()
    msg             = m.group("msg").strip()

    # ── sshd events ──
    if "sshd" in proc:
        fm = _RE_SSH_FAILED.search(msg)
        am = _RE_SSH_ACCEPTED.search(msg)
        im = _RE_SSH_INVALID.search(msg)
        dm = _RE_DISCONNECT.search(msg)

        if fm:
            rec["event_type"] = "login_failed"
            rec["user"]       = fm.group("user")
            rec["ip"]         = fm.group("ip")
            rec["status"]     = "failure"
            rec["message"]    = f"SSH login failed for user '{fm.group('user')}' from {fm.group('ip')}"
        elif am:
            rec["event_type"] = "login_success"
            rec["user"]       = am.group("user")
            rec["ip"]         = am.group("ip")
            rec["status"]     = "success"
            rec["message"]    = f"SSH login accepted for user '{am.group('user')}' from {am.group('ip')}"
        elif im:
            rec["event_type"] = "login_invalid_user"
            rec["user"]       = im.group("user")
            rec["ip"]         = im.group("ip")
            rec["status"]     = "failure"
            rec["message"]    = f"Invalid SSH user '{im.group('user')}' from {im.group('ip')}"
        elif dm:
            rec["event_type"] = "session_disconnect"
            rec["user"]       = dm.group("user")
            rec["ip"]         = dm.group("ip")
            rec["status"]     = "info"
            rec["message"]    = f"SSH disconnected: user='{dm.group('user')}' ip={dm.group('ip')}"
        else:
            rec["event_type"] = "ssh_event"
            rec["status"]     = "info"
            rec["message"]    = msg

    # ── sudo events ──
    elif "sudo" in proc:
        sm = _RE_SUDO.search(msg)
        if sm:
            rec["event_type"] = "privilege_escalation"
            rec["user"]       = sm.group("user")
            rec["status"]     = "success"
            rec["message"]    = f"sudo by '{sm.group('user')}': {sm.group('cmd').strip()}"
        else:
            rec["event_type"] = "sudo_event"
            rec["status"]     = "info"
            rec["message"]    = msg

    # ── PAM events ──
    elif "pam" in proc:
        pm = _RE_PAM_FAIL.search(msg)
        if pm:
            rec["event_type"] = "auth_failure"
            rec["user"]       = pm.group("user")
            rec["status"]     = "failure"
            rec["message"]    = f"PAM authentication failure for '{pm.group('user')}'"
        else:
            rec["event_type"] = "pam_event"
            rec["status"]     = "info"
            rec["message"]    = msg

    else:
        # Generic auth-header line we can at least timestamp
        rec["event_type"] = "auth_event"
        rec["status"]     = "info"
        rec["message"]    = msg

    return rec


# ── Syslog / Kernel / Application Format ─────────────────────────────
# Oct 10 13:55:36 appserver kernel: [12345.678] Out of memory: Kill process 999
# Oct 10 13:55:36 appserver cron[500]: (root) CMD (/usr/lib/cron/run-crons)
# Oct 10 13:55:36 appserver systemd[1]: Started Daily apt download activity.
# Oct 10 13:55:36 appserver CRON[1234]: pam_unix(cron:session): session opened for user root
_RE_SYSLOG = re.compile(
    r"(?P<ts>\w{3}\s+\d{1,2}\s+\d{2}:\d{2}:\d{2})"
    r"\s+(?P<host>\S+)"
    r"\s+(?P<proc>[^\[:]+)"
    r"(?:\[\d+\])?"
    r":\s+(?P<msg>.+)"
)
_RE_OOM      = re.compile(r"[Oo]ut of memory|Kill process (\d+)")
_RE_SEGFAULT = re.compile(r"segfault|Segmentation fault", re.IGNORECASE)
_RE_DISK     = re.compile(r"(I/O error|disk error|read error|write error)", re.IGNORECASE)
_RE_FIREWALL = re.compile(r"(iptables|DROPPED|REJECTED|firewall)", re.IGNORECASE)
_RE_SERVICE  = re.compile(r"(Started|Stopped|Failed|Restarting)\s+(.+)", re.IGNORECASE)

def parse_syslog(line: str) -> Optional[dict]:
    """Parse generic syslog lines (kernel, cron, systemd, etc.)."""
    m = _RE_SYSLOG.match(line)
    if not m:
        return None

    rec             = empty_record(line)
    rec["source"]   = "system"
    rec["category"] = "system"
    rec["timestamp"] = _syslog_ts_to_iso(m.group("ts"))
    proc            = m.group("proc").strip().lower()
    msg             = m.group("msg").strip()
    rec["message"]  = msg

    # Classify by process name and message content
    if "kernel" in proc:
        if _RE_OOM.search(msg):
            rec["event_type"] = "oom_kill"
            rec["status"]     = "critical"
        elif _RE_SEGFAULT.search(msg):
            rec["event_type"] = "segfault"
            rec["status"]     = "high"
        elif _RE_DISK.search(msg):
            rec["event_type"] = "disk_error"
            rec["status"]     = "high"
        elif _RE_FIREWALL.search(msg):
            rec["event_type"] = "firewall_event"
            rec["status"]     = "medium"
        else:
            rec["event_type"] = "kernel_event"
            rec["status"]     = "info"

    elif "cron" in proc:
        rec["event_type"] = "cron_job"
        rec["status"]     = "info"
        # Extract user from cron messages like (root) CMD ...
        cu = re.search(r"\((\w+)\)\s+CMD", msg)
        if cu:
            rec["user"] = cu.group(1)

    elif "systemd" in proc:
        sm = _RE_SERVICE.search(msg)
        if sm:
            action  = sm.group(1).lower()
            service = sm.group(2).strip()
            rec["event_type"] = f"service_{action}"
            rec["status"]     = "failure" if action == "failed" else "info"
            rec["message"]    = f"systemd: {action} '{service}'"
        else:
            rec["event_type"] = "systemd_event"
            rec["status"]     = "info"

    elif "NetworkManager" in m.group("proc") or "network" in proc:
        rec["event_type"] = "network_event"
        rec["category"]   = "network"
        rec["status"]     = "info"

    else:
        rec["event_type"] = "system_event"
        rec["status"]     = "info"

    return rec

# ─────────────────────────────────────────────────────────────────────
#  STAGE 2 – SOURCE DETECTION
# ─────────────────────────────────────────────────────────────────────

# Heuristics to identify log type before attempting to parse
_APACHE_HINTS = re.compile(
    r'^\S+\s+\S+\s+\S+\s+\[[^\]]+\]\s+"(?:GET|POST|PUT|DELETE|HEAD|OPTIONS|PATCH)\s'
)
_AUTH_HINTS = re.compile(
    r"\b(sshd|sudo|PAM|login|auth|passwd)\b", re.IGNORECASE
)
_SYSLOG_HINTS = re.compile(
    r"^\w{3}\s+\d{1,2}\s+\d{2}:\d{2}:\d{2}\s+\S+"
)

def detect_source(line: str) -> str:
    """
    Identify the probable source of a log line.

    Returns one of:  'apache' | 'auth' | 'syslog' | 'unknown'
    """
    if _APACHE_HINTS.match(line):
        return "apache"
    if _SYSLOG_HINTS.match(line):
        # Auth logs look like syslog but contain auth-specific process names
        if _AUTH_HINTS.search(line):
            return "auth"
        return "syslog"
    return "unknown"

# ─────────────────────────────────────────────────────────────────────
#  STAGE 4 – NORMALIZATION
# ─────────────────────────────────────────────────────────────────────

def normalize_record(rec: dict) -> dict:
    """
    Apply cross-cutting normalization rules to a parsed record.

    Rules applied:
     • Lowercase category, event_type, source
     • Strip leading/trailing whitespace from string fields
     • Replace empty strings with None
     • Validate IP address (set to None if malformed)
     • Ensure 'raw' is always a non-empty string
    """
    str_fields = ("source", "category", "event_type", "message",
                  "user", "ip", "status", "severity")
    for field in str_fields:
        val = rec.get(field)
        if isinstance(val, str):
            val = val.strip()
            rec[field] = val if val else None

    # Lowercase taxonomy fields
    for field in ("source", "category", "event_type", "severity"):
        if rec.get(field):
            rec[field] = rec[field].lower()

    # Validate IP
    if rec.get("ip") and not _valid_ip(rec["ip"]):
        rec["ip"] = None

    # Normalise hyphen-only auth user (Apache uses "-" for anonymous)
    if rec.get("user") == "-":
        rec["user"] = None

    return rec

# ─────────────────────────────────────────────────────────────────────
#  STAGE 5 – VALIDATION
# ─────────────────────────────────────────────────────────────────────

# Required fields that must be non-null for a record to be valid
_REQUIRED = ("timestamp", "source", "event_type", "message")

def validate_record(rec: dict) -> tuple:
    """
    Check a normalized record against validation rules.

    Returns (is_valid: bool, issues: list[str])
    """
    issues = []

    # Required fields
    for field in _REQUIRED:
        if not rec.get(field):
            issues.append(f"missing required field: '{field}'")

    # Timestamp format
    if rec.get("timestamp"):
        try:
            datetime.strptime(rec["timestamp"], "%Y-%m-%dT%H:%M:%SZ")
        except ValueError:
            issues.append(f"invalid timestamp format: '{rec['timestamp']}'")

    # IP validity (already normalised, but double-check)
    if rec.get("ip") and not _valid_ip(rec["ip"]):
        issues.append(f"invalid IP address: '{rec['ip']}'")

    return (len(issues) == 0, issues)

# ─────────────────────────────────────────────────────────────────────
#  STAGE 6 – TAGGING  (severity assignment)
# ─────────────────────────────────────────────────────────────────────

def assign_severity(rec: dict) -> dict:
    """
    Assign a severity label based on event type, status code, and
    message content.

    Severity ladder: critical > high > medium > low > info
    """
    et     = rec.get("event_type", "")
    status = str(rec.get("status", "") or "")
    msg    = (rec.get("message") or "").lower()

    # Critical
    if et in ("oom_kill",) or "out of memory" in msg:
        rec["severity"] = "critical"

    # High
    elif et in ("login_failed", "login_invalid_user", "auth_failure",
                "segfault", "disk_error", "http_server_error"):
        rec["severity"] = "high"
    elif status.startswith("5"):
        rec["severity"] = "high"

    # Medium
    elif et in ("http_client_error", "privilege_escalation",
                "firewall_event", "service_failed"):
        rec["severity"] = "medium"
    elif status.startswith("4"):
        rec["severity"] = "medium"

    # Low
    elif et in ("login_success", "session_disconnect", "http_write"):
        rec["severity"] = "low"

    # Info (default)
    else:
        rec["severity"] = "info"

    return rec

# ─────────────────────────────────────────────────────────────────────
#  FULL PIPELINE  (stages 2-6 chained together)
# ─────────────────────────────────────────────────────────────────────

def run_pipeline(raw_lines: list[str]) -> tuple[list[dict], dict]:
    """
    Process a list of raw log strings through all pipeline stages.

    Returns:
        records  – list of normalized record dicts
        stats    – pipeline statistics dict
    """
    records       = []
    stats = {
        "total_input":   len(raw_lines),
        "parsed":        0,
        "unparsed":      0,
        "valid":         0,
        "invalid":       0,
        "by_source":     {},
        "by_category":   {},
        "by_severity":   {},
        "validation_issues": [],
    }

    for line in raw_lines:
        line = line.rstrip("\n")
        if not line.strip():
            continue   # skip blank lines

        # ── Stage 2: detect ──────────────────────────────────────────
        src_type = detect_source(line)

        # ── Stage 3: parse ───────────────────────────────────────────
        rec = None
        if src_type == "apache":
            rec = parse_apache(line)
        elif src_type == "auth":
            rec = parse_auth(line)
        elif src_type == "syslog":
            rec = parse_syslog(line)

        if rec is None:
            # Unrecognised – create a minimal fallback record
            rec              = empty_record(line)
            rec["message"]   = line[:200]   # truncate very long lines
            rec["event_type"] = "unparsed"
            stats["unparsed"] += 1
        else:
            stats["parsed"] += 1

        # ── Stage 4: normalize ───────────────────────────────────────
        rec = normalize_record(rec)

        # ── Stage 5: validate ────────────────────────────────────────
        is_valid, issues = validate_record(rec)
        rec["valid"] = is_valid
        if not is_valid:
            stats["invalid"] += 1
            stats["validation_issues"].append({
                "id":     rec["id"],
                "raw":    line[:120],
                "issues": issues,
            })
        else:
            stats["valid"] += 1

        # ── Stage 6: tag severity ────────────────────────────────────
        rec = assign_severity(rec)

        # ── Accumulate counters ──────────────────────────────────────
        for key, bucket in [("source",   "by_source"),
                             ("category","by_category"),
                             ("severity","by_severity")]:
            label = rec.get(key, "unknown") or "unknown"
            stats[bucket][label] = stats[bucket].get(label, 0) + 1

        records.append(rec)

    return records, stats

# ─────────────────────────────────────────────────────────────────────
#  SAMPLE LOG GENERATOR
# ─────────────────────────────────────────────────────────────────────

def _ts_apache(offset_hours: int = 0) -> str:
    """Generate an Apache-style timestamp offset by N hours from now."""
    dt = datetime.now(timezone.utc) - timedelta(hours=offset_hours)
    return dt.strftime("%d/%b/%Y:%H:%M:%S +0000")

def _ts_syslog(offset_hours: int = 0) -> str:
    """Generate a syslog-style timestamp offset by N hours from now."""
    dt = datetime.now(timezone.utc) - timedelta(hours=offset_hours)
    return dt.strftime("%b %d %H:%M:%S")   # no year (standard syslog)

_IPS = [
    "192.168.1.101", "10.0.0.45", "172.16.5.22",
    "203.0.113.77",  "198.51.100.3", "185.220.101.5",
]
_USERS = ["alice", "bob", "root", "admin", "charlie", "eve"]
_PATHS = [
    "/index.html", "/login", "/api/v1/users", "/admin",
    "/.env", "/wp-login.php", "/etc/passwd", "/static/app.js",
]
_HTTP_METHODS = ["GET", "POST", "PUT", "DELETE"]
_HTTP_CODES   = [200, 200, 200, 301, 302, 400, 401, 403, 404, 500, 503]
_SERVICES     = [
    "nginx.service", "sshd.service", "cron.service",
    "mysql.service", "docker.service",
]

def generate_sample_logs(count: int = 40) -> list[str]:
    """
    Produce a realistic mixed batch of raw log lines.

    Includes intentional edge cases:
     • Malformed lines
     • Missing optional fields
     • Apache logs with unusual status codes
     • Multiple failed SSH attempts (brute-force pattern)
     • OOM and disk error syslog entries
    """
    random.seed(42)   # reproducible output for demo purposes
    lines = []

    # ── Apache web logs (roughly 40 % of batch) ───────────────────
    for i in range(max(1, count // 3)):
        ip     = random.choice(_IPS)
        user   = random.choice(["-", "-", "-", random.choice(_USERS)])
        ts     = _ts_apache(random.randint(0, 24))
        method = random.choice(_HTTP_METHODS)
        path   = random.choice(_PATHS)
        code   = random.choice(_HTTP_CODES)
        size   = random.randint(200, 50000)
        lines.append(
            f'{ip} - {user} [{ts}] "{method} {path} HTTP/1.1" {code} {size}'
        )

    # ── Auth / SSH logs (roughly 40 % of batch) ──────────────────
    for i in range(max(1, count // 3)):
        ts   = _ts_syslog(random.randint(0, 24))
        host = "webserver"
        ip   = random.choice(_IPS)
        user = random.choice(_USERS)
        pid  = random.randint(1000, 9999)

        choice = random.randint(0, 5)
        if choice == 0:
            lines.append(f"{ts} {host} sshd[{pid}]: Failed password for {user} from {ip} port 22 ssh2")
        elif choice == 1:
            lines.append(f"{ts} {host} sshd[{pid}]: Accepted publickey for {user} from {ip} port 22 ssh2")
        elif choice == 2:
            lines.append(f"{ts} {host} sshd[{pid}]: Invalid user hacker from {ip} port 22")
        elif choice == 3:
            cmd = "/bin/bash"
            lines.append(f"{ts} {host} sudo: {user} : TTY=pts/0 ; PWD=/home/{user} ; USER=root ; COMMAND={cmd}")
        elif choice == 4:
            lines.append(f"{ts} {host} PAM[{pid}]: Authentication failure; logname={user} uid=1001 euid=0")
        else:
            lines.append(f"{ts} {host} sshd[{pid}]: Disconnected from {user} {ip} port 22")

    # ── Syslog / System logs (roughly 20 % of batch) ──────────────
    syslog_templates = [
        lambda ts: f"{ts} appserver kernel: [12345.678] Out of memory: Kill process {random.randint(100,9999)} (java) score {random.randint(1,999)}",
        lambda ts: f"{ts} appserver kernel: [12345.678] EXT4-fs error (device sda1): ext4_find_entry:1455: inode #{random.randint(1,999)}: comm python: reading directory lblock 0",
        lambda ts: f"{ts} appserver kernel: [12345.678] Segmentation fault at address 0x{random.randint(0,0xFFFFFFFF):08x}",
        lambda ts: f"{ts} appserver kernel: [12345.678] iptables DROPPED IN=eth0 OUT= SRC={random.choice(_IPS)} DST=10.0.0.1 PROTO=TCP DPT=22",
        lambda ts: f"{ts} appserver cron[{random.randint(500,999)}]: (root) CMD (/usr/lib/cron/run-crons)",
        lambda ts: f"{ts} appserver systemd[1]: Started {random.choice(_SERVICES)}",
        lambda ts: f"{ts} appserver systemd[1]: Failed to start {random.choice(_SERVICES)}",
        lambda ts: f"{ts} appserver systemd[1]: Stopped {random.choice(_SERVICES)}",
    ]
    for i in range(max(1, count // 5)):
        ts = _ts_syslog(random.randint(0, 24))
        lines.append(random.choice(syslog_templates)(ts))

    # ── Edge-case / malformed lines ──────────────────────────────
    lines += [
        "",                                              # blank line
        "   ",                                           # whitespace only
        "This is not a log line at all.",                # garbage
        "2024-10-10T13:55:36Z UNKNOWN EVENT XYZ",        # unknown format
        f'999.999.999.999 - - [{_ts_apache(1)}] "GET /test HTTP/1.1" 200 100',  # invalid IP
    ]

    random.shuffle(lines)
    return lines

# ─────────────────────────────────────────────────────────────────────
#  DISPLAY / OUTPUT HELPERS
# ─────────────────────────────────────────────────────────────────────

def print_raw_logs(raw_lines: list[str]):
    """Print raw log lines with line numbers."""
    print(f"\n{C.BOLD}{SEP2}{C.RESET}")
    print(f"  RAW LOGS  ({len(raw_lines)} lines)")
    print(SEP2)
    for i, line in enumerate(raw_lines, 1):
        display = line[:110] + "…" if len(line) > 110 else line
        tag = f"{C.DIM}[{i:>3}]{C.RESET}"
        print(f"  {tag}  {display if display.strip() else C.DIM + '(blank)' + C.RESET}")
    print()


def print_normalized_record(rec: dict):
    """Pretty-print a single normalized log record."""
    sev    = rec.get("severity", "info")
    sc     = sev_colour(sev)
    valid  = rec.get("valid", False)
    v_icon = f"{C.GREEN}✓{C.RESET}" if valid else f"{C.RED}✗{C.RESET}"
    sim_tag = f"{C.DIM}(sim){C.RESET}" if rec.get("simulated") else ""

    print(f"  {C.BOLD}#{rec['id']:<4}{C.RESET}  "
          f"{sc}{sev.upper():<8}{C.RESET}  "
          f"{C.CYAN}{rec.get('source','?'):<12}{C.RESET}  "
          f"{rec.get('event_type','?'):<25}  "
          f"valid:{v_icon}  {sim_tag}")
    print(f"         ts      : {rec.get('timestamp') or C.DIM+'(missing)'+C.RESET}")
    print(f"         message : {rec.get('message','')[:90]}")
    if rec.get("ip"):
        print(f"         ip      : {rec['ip']}")
    if rec.get("user"):
        print(f"         user    : {rec['user']}")
    if rec.get("status"):
        print(f"         status  : {rec['status']}")
    print(f"         raw     : {C.DIM}{rec.get('raw','')[:90]}{C.RESET}")
    print()


def print_all_normalized(records: list[dict]):
    """Print every normalized record with a before/after comparison block."""
    if not records:
        print(f"\n  {C.YELLOW}No records to display.{C.RESET}\n")
        return

    print(f"\n{C.BOLD}{SEP2}{C.RESET}")
    print(f"  NORMALIZED LOG RECORDS  ({len(records)} records)")
    print(SEP2)
    print(f"  {'#':<5} {'SEV':<8} {'SOURCE':<12} {'EVENT TYPE':<25} {'VALID'}")
    print(f"  {SEP}")

    for rec in records:
        print_normalized_record(rec)


def print_before_after(raw_lines: list[str], records: list[dict]):
    """
    Show a side-by-side before/after transformation for the first N
    records that were successfully parsed (not 'unparsed').
    """
    SHOW = 6
    parsed_recs = [r for r in records if r.get("event_type") != "unparsed"][:SHOW]

    print(f"\n{C.BOLD}{SEP2}{C.RESET}")
    print(f"  BEFORE  vs  AFTER  (first {len(parsed_recs)} parsed records)")
    print(SEP2)

    for rec in parsed_recs:
        raw   = rec.get("raw", "")
        print(f"\n  {C.YELLOW}BEFORE{C.RESET} (raw):")
        print(f"  {C.DIM}{raw[:110]}{C.RESET}")
        print(f"\n  {C.GREEN}AFTER{C.RESET}  (normalized):")
        print_normalized_record(rec)
        print(f"  {SEP}")


def print_stats(stats: dict):
    """Display pipeline execution statistics."""
    total = stats["total_input"]

    print(f"\n{C.BOLD}{SEP2}{C.RESET}")
    print(f"  PIPELINE STATISTICS")
    print(SEP2)
    print(f"  Total input lines    : {total}")
    print(f"  Successfully parsed  : {C.GREEN}{stats['parsed']}{C.RESET}")
    print(f"  Unparsed / fallback  : {C.YELLOW}{stats['unparsed']}{C.RESET}")
    print(f"  Valid records        : {C.GREEN}{stats['valid']}{C.RESET}")
    print(f"  Invalid records      : {C.RED}{stats['invalid']}{C.RESET}")

    # Breakdown tables
    for label, bucket in [
        ("By Source",   "by_source"),
        ("By Category", "by_category"),
        ("By Severity", "by_severity"),
    ]:
        data = stats.get(bucket, {})
        if data:
            print(f"\n  {C.BOLD}{label}:{C.RESET}")
            for k, v in sorted(data.items(), key=lambda x: -x[1]):
                bar = "█" * min(v, 40)
                sc  = sev_colour(k) if bucket == "by_severity" else C.CYAN
                print(f"    {sc}{k:<18}{C.RESET}  {v:>4}  {C.DIM}{bar}{C.RESET}")

    # Validation failures
    issues = stats.get("validation_issues", [])
    if issues:
        print(f"\n  {C.BOLD}Validation Failures ({len(issues)}):{C.RESET}")
        for entry in issues[:10]:   # show max 10
            print(f"    #{entry['id']:<4}  {C.RED}{', '.join(entry['issues'])}{C.RESET}")
            print(f"           {C.DIM}{entry['raw'][:80]}{C.RESET}")
    print()

# ─────────────────────────────────────────────────────────────────────
#  EXPORT
# ─────────────────────────────────────────────────────────────────────

def export_to_json(records: list[dict], path: str = "normalized_logs.json"):
    """Serialize all normalized records to a JSON file."""
    if not records:
        print(f"\n  {C.YELLOW}Nothing to export.{C.RESET}\n")
        return
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(records, fh, indent=2, default=str)
    abs_path = os.path.abspath(path)
    print(f"\n  {C.GREEN}Exported {len(records)} records → {abs_path}{C.RESET}\n")

# ─────────────────────────────────────────────────────────────────────
#  SESSION STATE
# ─────────────────────────────────────────────────────────────────────

class PipelineSession:
    """Holds mutable state for the interactive session."""
    def __init__(self):
        self.raw_lines : list[str]  = []
        self.records   : list[dict] = []
        self.stats     : dict       = {}
        self.ran       : bool       = False

    def has_raw(self)  -> bool: return bool(self.raw_lines)
    def has_results(self) -> bool: return bool(self.records)

_session = PipelineSession()

# ─────────────────────────────────────────────────────────────────────
#  ACTION HANDLERS
# ─────────────────────────────────────────────────────────────────────

def action_generate_logs():
    """Generate a fresh batch of simulated log lines."""
    try:
        n_str = input("  How many log lines to generate? [default: 40]: ").strip()
        count = int(n_str) if n_str.isdigit() and int(n_str) > 0 else 40
    except (ValueError, EOFError):
        count = 40

    _session.raw_lines = generate_sample_logs(count)
    _session.records   = []
    _session.stats     = {}
    _session.ran       = False
    print(f"\n  {C.GREEN}Generated {len(_session.raw_lines)} raw log lines.{C.RESET}")
    print(f"  {C.DIM}(Run normalization from the menu to process them.){C.RESET}\n")


def action_load_file():
    """Load raw log lines from a user-specified text file."""
    path = input("  Enter path to log file: ").strip()
    if not path:
        print(f"  {C.RED}No path entered.{C.RESET}")
        return
    if not os.path.isfile(path):
        print(f"  {C.RED}File not found: {path}{C.RESET}")
        return
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as fh:
            lines = fh.readlines()
        _session.raw_lines = [l.rstrip("\n") for l in lines]
        _session.records   = []
        _session.stats     = {}
        _session.ran       = False
        print(f"\n  {C.GREEN}Loaded {len(_session.raw_lines)} lines from '{path}'.{C.RESET}\n")
    except OSError as exc:
        print(f"  {C.RED}Could not read file: {exc}{C.RESET}")


def action_run_pipeline():
    """Execute the normalization pipeline on the current raw logs."""
    if not _session.has_raw():
        print(f"\n  {C.YELLOW}No raw logs loaded.  "
              f"Generate or load logs first (options 1 / 2).{C.RESET}\n")
        return

    print(f"\n  {C.CYAN}Running pipeline on {len(_session.raw_lines)} lines …{C.RESET}")
    print(f"  {C.DIM}Stage 1: Input        ✓{C.RESET}")
    _session.records, _session.stats = run_pipeline(_session.raw_lines)
    print(f"  {C.DIM}Stage 2: Detection    ✓{C.RESET}")
    print(f"  {C.DIM}Stage 3: Parsing      ✓{C.RESET}")
    print(f"  {C.DIM}Stage 4: Normalization ✓{C.RESET}")
    print(f"  {C.DIM}Stage 5: Validation   ✓{C.RESET}")
    print(f"  {C.DIM}Stage 6: Tagging      ✓{C.RESET}")
    _session.ran = True

    st = _session.stats
    print(f"\n  {C.GREEN}Pipeline complete.{C.RESET}  "
          f"Parsed: {st['parsed']}  |  "
          f"Valid: {st['valid']}  |  "
          f"Invalid: {st['invalid']}\n")


def action_view_raw():
    if not _session.has_raw():
        print(f"\n  {C.YELLOW}No raw logs loaded yet.{C.RESET}\n")
        return
    print_raw_logs(_session.raw_lines)


def action_view_normalized():
    if not _session.has_results():
        print(f"\n  {C.YELLOW}No normalized records yet.  "
              f"Run the pipeline first (option 3).{C.RESET}\n")
        return

    choice = input(
        "  Display mode:\n"
        "   [1] Full normalized records\n"
        "   [2] Before vs After comparison\n"
        "  Select [1/2, default=1]: "
    ).strip()

    if choice == "2":
        print_before_after(_session.raw_lines, _session.records)
    else:
        print_all_normalized(_session.records)


def action_view_stats():
    if not _session.has_results():
        print(f"\n  {C.YELLOW}No statistics yet.  Run the pipeline first (option 3).{C.RESET}\n")
        return
    print_stats(_session.stats)


def action_export():
    if not _session.has_results():
        print(f"\n  {C.YELLOW}No records to export.  Run the pipeline first.{C.RESET}\n")
        return
    path_in = input("  Output file [default: normalized_logs.json]: ").strip()
    path    = path_in if path_in else "normalized_logs.json"
    export_to_json(_session.records, path)

# ─────────────────────────────────────────────────────────────────────
#  MAIN MENU
# ─────────────────────────────────────────────────────────────────────

MENU = [
    ("Generate sample logs",           action_generate_logs),
    ("Load logs from file",            action_load_file),
    ("Run normalization pipeline",     action_run_pipeline),
    ("View raw logs",                  action_view_raw),
    ("View normalized logs",           action_view_normalized),
    ("View pipeline statistics",       action_view_stats),
    ("Export normalized logs to JSON", action_export),
    ("Exit",                           None),
]

def print_menu():
    loaded_tag  = f"{C.GREEN}{len(_session.raw_lines)} lines loaded{C.RESET}" \
                  if _session.has_raw() else f"{C.DIM}no logs loaded{C.RESET}"
    ran_tag     = f"{C.GREEN}results ready{C.RESET}" \
                  if _session.has_results() else f"{C.DIM}not run{C.RESET}"

    print(f"\n{C.BOLD}  Main Menu{C.RESET}  "
          f"│ {loaded_tag}  │ pipeline: {ran_tag}")
    print(f"  {SEP[:50]}")
    for idx, (label, _) in enumerate(MENU, 1):
        print(f"  {C.CYAN}{idx}{C.RESET}.  {label}")
    print()


def main():
    banner()
    print(f"  {C.DIM}Pure Python · no external dependencies · "
          f"100%% stdlib{C.RESET}\n")

    while True:
        print_menu()
        try:
            choice = input("  Select option [1-8]: ").strip()
        except (KeyboardInterrupt, EOFError):
            print(f"\n\n  {C.DIM}Interrupted.  Goodbye!{C.RESET}\n")
            break

        if not choice.isdigit() or not (1 <= int(choice) <= len(MENU)):
            print(f"  {C.RED}Invalid choice.  Enter a number 1–{len(MENU)}.{C.RESET}")
            continue

        idx      = int(choice) - 1
        label, fn = MENU[idx]

        if fn is None:          # Exit
            print(f"\n  {C.DIM}Goodbye!{C.RESET}\n")
            break

        print(f"\n  {C.BOLD}» {label}{C.RESET}")
        fn()

# ─────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    main()